# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dseq',
                'doc_host': 'https://rraadd88.github.io',
                'git_url': 'https://github.com/rraadd88/dseq',
                'lib_path': 'dseq'},
  'syms': {'dseq.core': {'dseq.core.foo': ('core.html#foo', 'dseq/core.py')}}}
